### ISSUE TITLE
Draconic Evolution Reactor skript not working

### ISSUE THREAD

**Issue by LazerCorn3114** [FiskFille/Superheroes#10]
Hello I have currently been trying to use this skript someone made from my reactor from the mod draconic evolution however, it seems to not be working.

https://www.reddit.com/r/feedthebeast/comments/4g3uft/draconic_evolution_stable_12mil_rft_reactor_cc/?st=iwbk69it&sh=efee3a99

![image](https://cloud.githubusercontent.com/assets/16345693/20873793/41257184-ba60-11e6-9cbf-27ed844dbe39.png)

**Comment by FiskFille** [comment]
Uh? This is the FiskHeroes GitHub, not Draconic Evolution.
