### ISSUE TITLE
1.7.10 Armor Texture bug

### ISSUE THREAD

**Issue by ghost** [FiskFille/Superheroes#12]
![Armor Bug ](https://user-images.githubusercontent.com/108223024/175820660-5013ff74-8104-47bc-9a73-d07acd707c80.png)
![Armor Bug](https://user-images.githubusercontent.com/108223024/175820662-9f14588d-a30f-4a1a-85ff-c84e87d54957.png)

**Comment by FiskFille** [comment]
What other mods do you have installed?

**Comment by FiskFille** [comment]
Try removing Vic's Modern Warfare mod. Certain versions of it seem to mess with the armor models of other mods, for some reason.
