### ISSUE TITLE
Reverse Treadmill

### ISSUE THREAD

**Issue by EmrysGamer** [FiskFille/Superheroes#3]
Fisk! i found a bug where you reach a point of speedxp, you get degraded!

i used to have 4 (using barry flash, and before i got 34!?) speed levels and when i got a treadpoint i now have 3!

Also can you make the speedxp command remove speed 2?

like

more:

/speedxp 10L AlphaK9Gamer

less:

/speedxp remove *how many* *player*

anyways thanks!

**Comment by FiskFille** [comment]
To remove speed levels, do:
/speedxp -<amount>L

**Comment by EmrysGamer** [comment]
ok!

also what about the treadmill? its a bug!
