### ISSUE TITLE
internal server error when teleporting Sub-Atomic

### ISSUE THREAD

**Issue by runescapejon** [FiskFille/Superheroes#4]
i was on my server testing the mod with my friend and yea we both got htis internal server error and unable to join unless we both delete our playerdata 
http://pastebin.com/hrreSWAb

**Comment by FiskFille** [comment]
This is beyond my control.

**Comment by EmrysGamer** [comment]
Hahahhaa, Runescapejon Ask OmegaTron this he's the server admin!
