### ISSUE TITLE
Texture Issues

### ISSUE THREAD

**Issue by LazerCorn3114** [FiskFille/Superheroes#7]
When I put this mod with other mods aside from waila or NEI it has a texture problem with the suits.

https://gyazo.com/d34fc268f5ec2d0c3a6aff1cbe4cce21

**Comment by FiskFille** [comment]
I don't see any issue...?

**Comment by LazerCorn3114** [comment]
The Brown thing on my head is not part of my skin.

**Comment by runescapejon** [comment]
hm this is still a problem https://gyazo.com/a3faa17ed345221226d71d1559ecf576
is this fix in the upcoming update ?
