### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by ridler24** [FiskFille/Superheroes#9]
FiskFille,i have something to ask you.
i want (for private use only) have the coumpound bow and the quiver with his arrows in a mod (a mod that only contains the coumpound bow,the quiver and the arrows) can you please teach me how to do this ? if you don't want to help me,i will be okay with that.(and if you want to help me,i also want that the bow can charge rapidly and like a normal bow.

Ridler24

English is not my first language and i don't speak it like a pro so don't judge me if i do errors.

**Comment by FiskFille** [comment]
No.
